databases:
  - name: control_tareas_db
    databaseName: control_tareas_db
    user: control_tareas_user

services:
  - type: web
    name: control-py-tareas
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn CONTROL_PY_TAREAS.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: control_tareas_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
